-- MySQL Script generated by MySQL Workbench
-- Tue Feb 23 19:58:08 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema covoituragedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema covoituragedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `covoituragedb` DEFAULT CHARACTER SET utf8 ;
USE `covoituragedb` ;

-- -----------------------------------------------------
-- Table `Conducteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conducteur` (
  `idConducteur` INT NOT NULL AUTO_INCREMENT,
  `loginConducteur` VARCHAR(45) NOT NULL,
  `pwdConducteur` VARCHAR(45) NOT NULL,
  `nomConducteur` VARCHAR(100) NULL,
  `prenomConducteur` VARCHAR(100) NULL,
  `telConducteur` VARCHAR(12) NOT NULL,
  `adresseConducteur` VARCHAR(100) NULL,
  `emailConducteur` VARCHAR(45) NULL,
  `estFumeur` INT NOT NULL,
  PRIMARY KEY (`idConducteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Voiture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Voiture` (
  `idPassager` INT NOT NULL AUTO_INCREMENT,
  `marque` VARCHAR(45) NOT NULL,
  `modele` VARCHAR(45) NOT NULL,
  `nbPlaces` VARCHAR(45) NOT NULL,
  `matricule` VARCHAR(45) NOT NULL,
  `etat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPassager`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Voyage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Voyage` (
  `idVoyage` INT NOT NULL,
  `villeDepart` VARCHAR(100) NOT NULL,
  `villeArrivee` VARCHAR(100) NOT NULL,
  `dateVoyage` DATETIME NOT NULL,
  `prixVoyage` VARCHAR(45) NOT NULL,
  `etatVoyage` INT NOT NULL,
  `Conducteur_idConducteur` INT NOT NULL,
  `Voiture_idPassager` INT NOT NULL,
  PRIMARY KEY (`idVoyage`),
  INDEX `fk_Voyage_Conducteur_idx` (`Conducteur_idConducteur` ASC),
  INDEX `fk_Voyage_Voiture1_idx` (`Voiture_idPassager` ASC),
  CONSTRAINT `fk_Voyage_Conducteur`
    FOREIGN KEY (`Conducteur_idConducteur`)
    REFERENCES `Conducteur` (`idConducteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voyage_Voiture1`
    FOREIGN KEY (`Voiture_idPassager`)
    REFERENCES `Voiture` (`idPassager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
